#!/bin/bash
filePath=$(pwd)"/../server"
uiFilePath=$(pwd)"/../client/basic/src"
port="80"
container="devbox"
name=$(echo $(whoami)"-"$(date "+%F-%T")| sed -r 's/[:]+/./g')
network="dbnet"
docker run -it --name $name \
	--net=$network \
	-v $filePath:/usr/src/app/server \
	-v $uiFilePath:/usr/src/app/server/src \
	-p $port:3000 \
	$container
