version: "3.3"
services:
  roach1:
    container_name: roach1
    image: cockroachdb/cockroach:v20.1.3
    command: start --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - ./cockroach-data/roach1:/cockroach/cockroach-data
    networks:
      roachnet:
        aliases:
          - roach1

  roach2:
    container_name: roach2
    image: cockroachdb/cockroach:v20.1.3
    command: start --insecure --join=roach1
    volumes:
      - ./cockroach-data/roach2:/cockroach/cockroach-data
    depends_on:
      - roach1
    networks:
      roachnet:
        aliases:
          - roach2

  roach3:
    container_name: roach3
    image: cockroachdb/cockroach:v20.1.3
    command: start --insecure --join=roach1
    volumes:
      - ./cockroach-data/roach3:/cockroach/cockroach-data
    depends_on:
      - roach1
    networks:
      roachnet:
        aliases:
          - roach3

  node1:
    container_name: node1
    image: devbox
    working_dir: /usr/src/app/server
    command: sh -c "npm install && npm run db-setup && npm run build && npm start"
    depends_on:
      - roach1
    volumes:
      - ../server:/usr/src/app/server
      - ../client/login/src:/usr/src/app/server/src
    ports:
      - 80:3000
    networks:
      - roachnet


networks:
  roachnet:
    driver: bridge
    attachable: true
